name: mobsfscan

on:
  push:
    branches: [ master, feature/implement-sast-into-pipeline ]
  pull_request:
    branches: [ master, feature/implement-sast-into-pipeline ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: mobsfscan
        uses: MobSF/mobsfscan@main
        with:
          args: '. --json'