name: Release App

on:
  push:
    branches:
      - main
      - feature/implement-bundle-generator-into-pipeline

jobs:
### BUILD ###
  build_and_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Sources
      uses: actions/checkout@v3
      with:
        # Number of commits to fetch. 0 indicates all history for all branches and tags.
        fetch-depth: 0

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    # Cache Gradle dependencies and Gradle Wrapper
    - name: Setup Gradle Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
            ${{ runner.os }}-gradle-

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload Test Reports Folder
      uses: actions/upload-artifact@v3
      if: ${{ always() }} # IMPORTANT: Upload reports regardless of status
      with:
        name: reports
        path: app/build/test-results # path to where the xml test results are stored

  #Generate Bundle
    - name: Generate App Version Name
      run: echo "VERSION_NAME=$(git describe --tags | sed 's/\(.*\)-/\1./' | sed 's/\(.*\)-/\1+/')" >> $GITHUB_ENV

    - name: Bump Version
      uses: chkfung/android-version-actions@v1.2.1
      with:
        gradlePath: app/build.gradle
        versionCode: ${{ github.run_number }}
        versionName: ${{ env.VERSION_NAME }}

      # Restore jks
    - name: Restore playstore.keystore.jks
      run: echo ${{ secrets.SIGNING_KEY }} | base64 -d > playstore.keystore.jks

      # Build Release AAB
    - name: Build Release AAB
      run: ./gradlew
        -PKEYSTORE_FILE=playstore.keystore.jks
        -PKEYSTORE_PASSWORD=${{ secrets.KEY_STORE_PASSWORD }}
        -PSIGNING_KEY_ALIAS=${{ secrets.ALIAS }}
        -PSIGNING_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}
        app:bundleRelease

      # Upload Bundle
    - name: Upload Bundle Reports Folder
      uses: actions/upload-artifact@v3
      with:
        name: release
        path: app/build/outputs/bundle/release

### REPORTS ###
  report:
    runs-on: ubuntu-latest
    needs: build_and_unit_tests # The report job will run after test job
    if: ${{ always() }} # IMPORTANT: Execute report job regardless of status
    steps:
    - name: Download Test Reports Folder
      uses: actions/download-artifact@v3
      with:
        name: reports

    - name: Android Test Report
      uses: asadmansr/android-test-report-action@v1.2.0

    - name: Download Bundle
      uses: actions/download-artifact@v3
      with:
        name: release